export type APIResponse = {
    avg_response: number,
    check_interval: number,
    created_at: string,
    failures_24_hours: number,
    group_id: number,
    incidents: [],
    last_error: string,
    last_success: string,
    latency: number,
    messages: [],
    online_24_hours: number,
    online_7_days: number,
    order_id: number,
    permalink: string,
    ping_time: number,
    public: boolean,
    stats: {
        failures: number,
        hits: number,
        first_hit: string,
    },
    id: number,
    name: string,
    online: boolean,
    status_code: number,
    updated_at: string,

}